version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: nataly-33
      MONGO_INITDB_ROOT_PASSWORD: passWord&3
    volumes:
      - mongo_data:/data/db
    restart: always

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      MONGO_URI: "mongodb://nataly-33:passWord&3@mongodb:27017"
    depends_on:
      - mongodb
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "5174:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: always

volumes:
  mongo_data:
